
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/campusconnect
    username: postgres
    password: FE23A038
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8080

